title: "Your title" # Change title of your site here
description: "Write an description for your new site here."
baseurl: "/jekyll-starter" # The subpath of your site. It should be used when the resulting site lives at the subpath of the domain. E.g. if your site lives at example.com/blog, please use baseurl: "/blog". If your site lives at example.com, please leave baseurl empty (baseurl: "").
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
highlighter: rouge
